/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanjeevaniapp.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Toolkit;
import java.util.Random;
import javax.swing.JComponent;
import javax.swing.UIManager;

/**
 *
 * @author Ramkumar
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        setLocationRelativeTo(null);

        UIManager.put("nimbusOrange", new Color(0, 255, 0));
        SplashThread obj = new SplashThread();
        obj.start();
        Image icon = Toolkit.getDefaultToolkit().getImage("src/sanjeevaniapp/icons/Logo4.png");    
        this.setIconImage(icon); 
        this.setResizable(false);
       
        
//        JProgressBar progressBar = new JProgressBar();

        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lblProcessState = new javax.swing.JLabel();
        lblProcessPercent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("     Sanjeevani Application");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 470, 70));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevaniapp/icons/HomePageBG.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -170, 970, 710));

        jProgressBar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(0, 153, 0));
        jProgressBar1.setOpaque(true);
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 890, 20));

        lblProcessState.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProcessState.setForeground(new java.awt.Color(102, 102, 102));
        lblProcessState.setText("Connecting to Database......");
        jPanel1.add(lblProcessState, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 280, 20));

        lblProcessPercent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProcessPercent.setForeground(new java.awt.Color(0, 153, 0));
        lblProcessPercent.setText("Loading... 100%");
        jPanel1.add(lblProcessPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 540, 120, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblProcessPercent;
    private javax.swing.JLabel lblProcessState;
    // End of variables declaration//GEN-END:variables
class SplashThread extends Thread{
    public void run(){
        int count=1;
        Random rand = new Random();
        UIManager.put("jProgressBar1.foreground", Color.GREEN);
        jProgressBar1.updateUI();
        jProgressBar1.setForeground(Color.green);
        while(jProgressBar1.getValue()<jProgressBar1.getMaximum()){
            
            if(count<30)
            {
                lblProcessState.setText("Loading programm files....");
            }
            else if(count<50)
            {
                lblProcessState.setText("Loading Libraries.....");
            }
            else if(count<65)
            {
                lblProcessState.setText("Opining Programm files.....");
            }
            else if(count<75)
            {
                lblProcessState.setText("Connecting to Database......");
            }
            else if(count<90)
            {
                lblProcessState.setText("Opening App.....");
            }
            if(count<99)
            lblProcessPercent.setText("Loading... "+count+" %");
            else
            lblProcessPercent.setText("Loading... 100 %");
            jProgressBar1.setValue(count);
            count+=rand.nextInt(10);
            try{
                Thread.sleep(200);
                
            }catch(InterruptedException ex)
            {
                System.out.println("Exception in SplashThread!"+ex);
            }
        }
        LoginFrame f =new LoginFrame();
        f.setVisible(true);
        dispose();
    }
    
}}
